### ISSUE TITLE
Changing penColor changes existing paths

### ISSUE THREAD

**Issue by piperone** [wobsoriano/v-perfect-signature#5]
I implemented a very simple color-picker and paired it with v-perfect-signature. Looking at [Perfect Freehand's example page](https://perfect-freehand-example.vercel.app/), it is possible to draw paths with different colors onto the canvas. Is it possible to do this with v-perfect-signature as well? Currently, when modifying the `penColor`-prop, it affects **all** existing paths. 

Example:

![Oct-12-2021 02-49-38](https://user-images.githubusercontent.com/351744/136873145-7cf8b601-97c9-4c85-911d-dad6dc20cf27.gif)

Thanks!

**Comment by wobsoriano** [comment]
I based my implementation on https://github.com/szimek/signature_pad. If you want more control I think it's better if you use vanilla perfect-freehand

**Comment by platform-kit** [comment]
@wobsoriano did you ever take action on this? If not, can you point me in the right direction as to how to accomplish this with your package?
