### ISSUE TITLE
Question: Where can I get a Vue2 CDN / <script> tag usable compilation for this?

### ISSUE THREAD

**Issue by Mashiane** [wobsoriano/v-perfect-signature#9]
Hi there

Where can I get a Vue2 CND / script tag compatible library for this?

Thank you so much!

**Comment by wobsoriano** [comment]
https://unpkg.com/v-perfect-signature@1.4.0/dist/index.global.js
https://cdn.jsdelivr.net/npm/v-perfect-signature
